name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 18
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: node --version
      - run: npm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
