name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --output _dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
